name = input("what is your name:")
age = input("how old are you:")
height = input("how tall are you:")
student = input("are you a student:")
age = int(age)
height = float(height)
print(f"hello {name}, you are {age} years old, {height}m tall,你{student} a student.")
print("\n===== Your Profile =====")
print(f"Name:   {name}")
print(f"Age:    {age}")
print(f"Height: {height:.2f}m") 
print(f"Student: {student}")
print("=========================")